xdata/briefing.xd, xdata/man2.xd
=> Kerry readables 002

build.ps1, maps/man2.darkradiant
=> change fire pit light texture

build.ps1, guis/mainmenu_custom_defs.gui, sound/ambient.sndshd
=> custom menu

maps/man2.darkradiant
=> fix z-fighting in house at back of Inn

maps/man2.darkradiant
=> Let Ingleby Sr door open wider, add monsterclip, and nodraw over carpet

maps/man2.darkradiant
=> fix floating stool in Highclere staff area

maps/man2.darkradiant
=> fix trim poking through Percy's fireplace

maps/man2.darkradiant
=> fix z-fighting in Ingleby office

maps/man2.darkradiant
=> fix z-fighting in Highclere staff rooms

maps/man2.darkradiant
=> fix z-fighting in T's secret tunnel

maps/man2.darkradiant
=> fix gap in support in end area building

maps/man2.darkradiant
=> user shinier goblets for loot on T's back patio

maps/man2.darkradiant
=> change texture alignment on tunnel ceiling

maps/man2.darkradiant, maps/man2.script
=> make Dalton's stew always frobable

maps/man2.darkradiant
=> change window and add tiny bit of loot to begger house at end

darkmod.txt, maps/man2.darkradiant
=> get rid of lightgem difficulty increase

maps/man2.darkradiant, xdata/man2.xd
=> get rid of note on Inn door

darkmod.txt, maps/man2.darkradiant
=> fix being able to frob light switches through wall in mansion

maps/man2.darkradiant
=> fix visportal showing on Inn roof trap door

maps/man2.darkradiant
=> fix z-fighting on outer walls

maps/man2.darkradiant
=> fix floating cutlery in Ingleby dining room

maps/man2.darkradiant
=> fix Ingleby's sister's desk contents sunk into bottom of desk
